name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main   # Deploy when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./my_portfolio

      - name: Build Flutter Web
        run: flutter build web --release --base-href /my_portfolio/
        working-directory: ./my_portfolio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my_portfolio/build/web